<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <Compile Include="../../Medium/MythicSpirits.cs" Link="Production/MythicSpirits.cs" />
    <Compile Include="../../Medium/MythicInfluence.cs" Link="Production/MythicInfluence.cs" />
    <Compile Include="../../Utilities/Guids.cs" Link="Production/Guids.cs" />
  </ItemGroup>
</Project>
